### PR TITLE
Adding readme and fragment abort changes

### PR DESCRIPTION
**Pull request by schmintendo**
Added README changes (lots of changes, IA stuff, etc.)

Also added fragment abort changes as discussed in Discord.  These changes are in line with the README.

### CODE REVIEW

**Comment by schmintendo** [comment]
added credits too :)

**Comment by schmintendo** [comment]
don't mind those two commits I made after the previous comment, they're unneeded.

**Comment by schmintendo** [comment]
FINALLY DONE, please merge this.

**Comment by i3p9** [comment]
Done, thanks so much!

**Pull request merged**
